### ISSUE TITLE
branch v0.7: vibrancy: 'light', transparent: true setting kills tab bar. 

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#341] opened 2017-03-06 23:30 UTC
Operation System: ubuntu 16.10
Beaker Version: branch v0.7 3b0dc78adf9d5705f6b4c7571831de9799bdc3c5

see: https://github.com/beakerbrowser/beaker/commit/1ac2bf4850485ba5d7b90dfad2d7e4c1a86e6a35#commitcomment-21145844

I'm sorry, but it's unusable.

**Comment by pmario** [comment] 2017-03-06 23:31
![toolbar problem](https://cloud.githubusercontent.com/assets/374655/23634953/5e973de6-02cd-11e7-87d2-4fa241e98521.png)

**Comment by pfrazee** [comment] 2017-03-07 04:12
This is a duplicate of https://github.com/beakerbrowser/beaker/issues/326. We'll hit it soon. Thanks for reporting

**Closed by pfrazee** 2017-03-07 04:12 UTC
