### ISSUE TITLE
Windows Build 

### ISSUE THREAD

**Issue by fredhampton** [beakerbrowser/beaker#103] opened 2016-09-23 00:53 UTC
Operation System:OSX
Beaker Version:Latest from Master

Is there a way to build for windows ?

**Comment by pfrazee** [comment] 2016-09-23 16:31
Hey Fred, it *should* be possible to do by just running `npm run release` on a windows machine. If you run into any surprises, let me know. I havent tried it yet.

**Comment by pfrazee** [comment] 2016-09-23 22:04
I just glanced at the build docs and noticed that's not right. I'll need to make a release-build command for windows

**Comment by fredhampton** [comment] 2016-10-15 23:20
Is it possible to build for windows now ?

**Comment by pfrazee** [comment] 2016-10-16 02:55
You still need to build from source, manually.

**Comment by rocketinventor** [comment] 2017-01-19 02:19
On the website, it still says mac & Linux only. An actual Windows build or reference would be nice.

**Comment by pfrazee** [comment] 2017-01-19 16:24
@rocketinventor soon, I hope

**Comment by pmario** [comment] 2017-02-13 23:10
@fredhampton 

have a look at: https://github.com/beakerbrowser/beaker/issues/55#issuecomment-279546294 ... it's a bit hacky but worked for me. 

The problem is, that depending on your installed software, you may miss more or less dependencies.

**Comment by pfrazee** [comment] 2017-08-03 15:34
Closing as a duplicate of https://github.com/beakerbrowser/beaker/issues/55

**Closed by pfrazee** 2017-08-03 15:34 UTC
Labels: enhancement
