### ISSUE TITLE
Can't import files into new site

### ISSUE THREAD

**Issue by jcalfee** [beakerbrowser/beaker#718] opened 2017-10-23 18:17 UTC
Operation System: ubuntu 16.04
Beaker Version: 
Version: 0.7.6 Electron: 1.7.4 - Chromium: 58.0.3029.110 - Node: 7.9.0

I'm running from git clone via `npm start`.  I choose New Site and (unlike the video) I'm not prompted for the title and description, it instead shows a new dat file and url:

![image](https://user-images.githubusercontent.com/204121/31905540-26b2fa0a-b7f4-11e7-9f42-c34b87860d2d.png)

I can go to import files and find a folder and click Import:
![image](https://user-images.githubusercontent.com/204121/31905578-45b500c4-b7f4-11e7-8208-ca4bb1546bbd.png)

The folder chooser dialog above dispersals but the folder or file does not import.

No errors in `.config/Beaker Browser/debug.log`

**Comment by pfrazee** [comment] 2017-10-23 18:43
This is a duplicate of https://github.com/beakerbrowser/beaker/issues/668. Linux doesnt support import dialogs which can select both files and folders, which screws us up here. We're going to have to make a custom file picker.

**Comment by pfrazee** [comment] 2017-10-23 18:44
For the moment, the only solution is to import the entire folder.

**Closed by pfrazee** 2017-10-23 18:43 UTC

**Comment by jcalfee** [comment] 2017-10-23 18:56
The tag 0.7.5 works:
https://github.com/beakerbrowser/beaker/issues/668#issuecomment-324437262

thanks..
