### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by iBilley** [beakerbrowser/beaker#1471] opened 2019-10-18 23:23 UTC
Operating system: manjaro linux

This is:

- [ ] a bug
- [ x] general feedback
i have low vision

i would love to see a dark theme option inside beaker. i currently use firefox and have it tweaked so its respecting my dark theme and together with a darkreader plugin this works 99% of the time.

beaker is electron app and defaults to a standard GTK or QT white theming?. because its sandboxed frm the os ? 

would be nice to see a GTK/QT theme chooser.

**Comment by pfrazee** [comment] 2019-10-21 15:06
After the next major release (0.9) I plan to get this on the roadmap

**Comment by Ornataweaver** [comment] 2019-11-12 21:23
Duplicate of https://github.com/beakerbrowser/beaker/issues/1035

**Closed** 2020-05-06 16:28 UTC
Labels: enhancement
