### ISSUE TITLE
forking site popup crops buttons

### ISSUE THREAD

**Issue by seekr** [beakerbrowser/beaker#902] opened 2018-03-20 22:18 UTC
Operation System: windows 10
Beaker version: 0.8.0 pre3

When forking a site the popup is not large enough to show the buttons. See screenshot below.

![bug](https://user-images.githubusercontent.com/2786460/37685706-303fbb6e-2c73-11e8-906e-10a14980945f.PNG)

**Comment by taravancil** [comment] 2018-03-20 22:45
Duplicate of #874

**Closed by taravancil** 2018-03-20 22:45 UTC
