### ISSUE TITLE
On Debian, Beaker "Starting..." but the user interface does not show up

### ISSUE THREAD

**Issue by jcalfee** [beakerbrowser/beaker#1321] opened 2019-01-17 14:09 UTC
Operation System: Debian GNU/Linux 9 (stretch)
Beaker version: 0.8.2
Node: v11

I just see Starting... but no GUI.  I waited at least 2 minutes.

```bash
$ ./opt/beaker-browser-0.8.2-x86_64.AppImage
[ dat-daemon ] Starting...
^C
```

When building the 0.8.2 tag from source I get the same behavior:
```bash
$ npm start
 
> beakerbrowser@ start /home/gamer/opt/beaker
> gulp start
 
[07:57:05] Using gulpfile ~/opt/beaker/gulpfile.js
[07:57:05] Starting 'start'...
[07:57:05] Starting '<anonymous>'...
Spawning electron /home/gamer/opt/beaker/node_modules/electron/dist/electron
[ dat-daemon ] Starting...
^C
```

By the way, the snap worked..

**Comment by jcalfee** [comment] 2019-01-17 14:38
Related https://github.com/beakerbrowser/beaker/issues/1319

**Comment by pfrazee** [comment] 2019-01-17 16:02
Thanks for filing, I'm going to close this as a duplicate of #1319.

**Closed** 2019-01-17 16:02 UTC
Labels: bug, duplicate, linux
