### ISSUE TITLE
Beaker doesn't initialize when I'm offline

### ISSUE THREAD

**Issue by kewitz** [beakerbrowser/beaker#854] opened 2018-02-16 21:02 UTC
Operation System: MacOS High Sierra 10.13.3
Beaker Version: 0.7.11

1. I'm disconnected;
2. I open Beaker;
3. The electron frame shows up;
4. There's no starting page, no address bar and no menu bar.

![screen recording 2018-02-16 at 03 55 pm](https://user-images.githubusercontent.com/2119706/36329045-7ef3428a-1332-11e8-9713-2fa7055e460f.gif)

**Comment by pfrazee** [comment] 2018-03-23 22:44
I'm not able to reproduce this on Beaker 0.8.0 on Sierra. I'm going to assume it's fixed in latest (hopefully true!). If not, please feel free to reopen.

Thanks for reporting!

**Closed by pfrazee** 2018-03-23 22:44 UTC
Labels: bug
