### ISSUE TITLE
Cannot build on Debian

### ISSUE THREAD

**Issue by clemsos** [beakerbrowser/beaker#181] opened 2016-11-12 15:39 UTC
Operation System: Linux 4.3.0-1-amd64 #1 SMP Debian 4.3.3-5 (2016-01-04) x86_64 GNU/Linux
Beaker Version: 0.4.1 / 0.4.2

Cannot build on fresh install - seems to crash because of Electron. Any idea ?

```
  ~/Dev/beaker ‹› ‹ab2aa3c› 
╰─$ npm install

> electron@1.4.6 postinstall /home/clemsos/Dev/beaker/node_modules/electron
> node install.js

Downloading electron-v1.4.6-linux-x64.zip
Error: GET https://github.com/beakerbrowser/electron/releases/download/v1.4.6/electron-v1.4.6-linux-x64.zip returned 404
/home/clemsos/Dev/beaker/node_modules/electron/install.js:22
  throw err
  ^

Error: Failed to find Electron v1.4.6 for linux-x64 at https://github.com/beakerbrowser/electron/releases/download/v1.4.6/electron-v1.4.6-linux-x64.zip
    at Request.<anonymous> (/home/clemsos/Dev/beaker/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/home/clemsos/Dev/beaker/node_modules/request/request.js:986:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
```

**Comment by pfrazee** [comment] 2016-11-12 15:53
Yeah, I know what the issue is. Beaker uses a custom fork of Electron, which has some updates that haven't yet landed in GitHub's canonical version. This is great for getting features & fixes shipped, but it means I need to build the electron binary for all platforms, which I'm not yet able to do. (I don't have the resources yet ☹️ )

I can think of a couple of options:

 1. I could setup a guide for you to build Electron yourself. It's possible to specify the electron path used with an env var (ELECTRON_PATH), so you could clone Beaker's electron fork, build it, and then run Beaker by setting the env var. This will be a PITA for you, and there's a good chance you'll have bugs when you get Beaker running, because I haven't tested on Debian yet. But, I can help you get through it.
 2. I could whip up a branch for you that uses vanilla Electron. Most of our custom Electron build has been upstreamed to GitHub at the moment, so you probably won't notice the difference. Obviously not a permanent solution, but it'd work for now.
 3. Hang tight until I get the resources to build for multiple platforms.

I'm happy to go with any option, just let me know. I'm sorry I don't have the build working for you yet!

**Comment by clemsos** [comment] 2016-11-12 16:35
Well, I can start by building Electron myself if you can indicate me some steps. Also, a branch with stable electron could be also useful for others. About the 3rd option (to wait) : I will prefer to start using beaker soon of course :)  Thanks !

**Comment by pfrazee** [comment] 2016-11-12 16:45
Hmm. I started to write those instructions, and realized you'd have to modify some files, and we might as well just use option 2 at that point! One moment while I put together that branch.

**Comment by pfrazee** [comment] 2016-11-12 16:56
Ok, instructions are as follows:

```
cd $beaker_dir
git checkout --track origin/vanilla
npm run burnthemall
npm start
```

Good luck! LMK what else breaks.

**Comment by clemsos** [comment] 2016-11-12 17:15
Works ! Thanks, awesome :)
I am going to try IPFS now
 
![selection_194](https://cloud.githubusercontent.com/assets/743246/20239586/fae5a206-a903-11e6-81be-466359dd95a9.png)

**Comment by pfrazee** [comment] 2016-11-12 17:22
Great! Not too pretty with that menu bar but hey. Add that to the TODOs.

(IPFS support is pretty rudimentary but it works. You'll need to have the daemon running. I much prefer Dat.)

**Comment by clemsos** [comment] 2016-11-12 17:33
cool ! I am sort of new to all this. last time I tried Dat was a year ago and it seems a ttly different project now :)  I dont get the difference between the both... also I saw you had a doc on dat VS ipfs previously but it was removed, right ? 

For IPFS, I installed the plugin. Should just have to input sth like in the browser ipfs://QmezCUJW1CEbyHopF83pGJKxoj46je3AyDVjwTnZ6SQ6T5 ?

**Comment by pfrazee** [comment] 2016-11-12 17:56
> I am sort of new to all this. last time I tried Dat was a year ago and it seems a ttly different project now :)

Hah yeah, that's an interesting story that I hope Max (the dat organizer) will tell on tape someday. They found scientists really preferred to work with unstructured data, so they gradually moved more into p2p file-sharing. @mafintosh got involved, and he integrated a lot of the ideas from BitTorrent, IPFS, Secure Scuttlebutt, and Certificate Transparency. There's a pretty good overview here: https://beakerbrowser.com/docs/dat/intro.html

> I dont get the difference between the both... also I saw you had a doc on dat VS ipfs previously but it was removed, right ?

Yeah I just need to get a new document uploaded. Dat has a few standout differences: 1. the archives are versioned with an immutable changelog in the metadata; 2. the archives have some good encryption & secrecy properties, see my linked doc; 3. the URLs are nicer (explained below); 4. it's in JS, so I dont need to run a daemon w/beaker; 5. Dat's a grant-funded non profit.

> For IPFS, I installed the plugin. Should just have to input sth like in the browser ipfs://QmezCUJW1CEbyHopF83pGJKxoj46je3AyDVjwTnZ6SQ6T5 ?

Plugin is installed by default, actually. You just need to run the IPFS daemon separately. I havent been testing their releases, so let me know if there's a bug.

IPFS URLs are kind of weird. It's actually like this, IIRC: `ipfs:/ipfs/QmezCUJW1CEbyHopF83pGJKxoj46je3AyDVjwTnZ6SQ6T5`

They're not standard URLs. (See my item 3 as to why I prefer dat.)

**Comment by clemsos** [comment] 2016-11-12 18:19
thanks for all the info ! Interesting pivot for Dat, which makes complete sense and broaden the scope of possible uses. I will read through the docs more carefully and see how I can continue to use dat and beaker :) I am thinking of using it for exchanging data during events with a share rep for all event. Do you think it make sense ?

**Comment by pfrazee** [comment] 2016-11-12 18:41
Could probably work, explain a little more for me: Is the use-case that, you're at an event, and participants are sharing data with an organizer ("share rep")?

**Comment by clemsos** [comment] 2016-11-12 18:51
Sorry, was unclear. The scenario is more  : you have several events happening at the same time in different places in the world, can people use a single dat rep to share files in "real-time" ? 

Let's say there is 3 people in 3 different cities. Each of them is adding / modifying files in the same dat folder/rep. Will dat be able to keep the folder in sync so everyone can see the latest changes ?

**Comment by pfrazee** [comment] 2016-11-12 19:02
Oh yeah, so that's called "Multiwriter" mode. It's not implemented in the protocol yet; it'll be a while, I imagine.

What you could do is, have each person create their own dat, and then, in your application, merge those dats together. It'd take some work to make merging work nicely (I'm happy to help with that, and add features if you need them) but it is doable.

**Comment by clemsos** [comment] 2016-11-12 19:06
OK ! I am going to do a bit more testing with dat and beaker and will get back to you when all this is clearer. Thanks again !

**Closed** 2016-11-12 19:06 UTC
Labels: bug
