### ISSUE TITLE
Not able to publish/share website.

### ISSUE THREAD

**Issue by TheOneAboveAllTitan** [beakerbrowser/beaker#1082] opened 2018-07-18 08:59 UTC
Operation System: Xubuntu 32 bit
Beaker version: 0.8.0-prerelease.6 Electron: 2.0.2 - Chromium: 61.0.3163.100 - Node: 8.9.3

"Publish" button as told in documentation is not visible. When I shared URL of my webpage, the website didn't opened at my friends computer. But when uploaded the site on hashbase, I was able to view my website atleast on HTML.
My website URL : dat://edd9b09cca6aadb281caa2c7f6c9c1fe3a47fac0d74a783fe3f7833b61fcbef8/
Hashbase URL : dat://fyghjbmkuydfgfhvcdfg.hashbase.io
                           https://fyghjbmkuydfgfhvcdfg.hashbase.io
@pfrazee

**Comment by pfrazee** [comment] 2018-07-18 17:21
We're still working on the reliability of peer connections -- sometimes networks are just too hostile to p2p. Hashbase tends to solve the problem because it's a public peer that users can reliably connect to. We're working hard on improving the reliability overall.

Closing as a duplicate of https://github.com/beakerbrowser/beaker/issues/1081.

**Closed by pfrazee** 2018-07-18 17:21 UTC
