### ISSUE TITLE
After crash, can't start browser

### ISSUE THREAD

**Issue by aaronshaf** [beakerbrowser/beaker#715] opened 2017-10-20 14:49 UTC
OS: OSX 10.12.6
Beaker Version: Latest?

```
Uncaught Exception:
TypeError: Cannot read property 'getPrimaryDisplay' of null
    at defaultState (/Applications/Beaker Browser.app/Contents/Resources/app/background-process.build.js:3908:31)
    at restoreState (/Applications/Beaker Browser.app/Contents/Resources/app/background-process.build.js:3904:28)
    at createShellWindow (/Applications/Beaker Browser.app/Contents/Resources/app/background-process.build.js:3817:60)
    at ensureOneWindowExists (/Applications/Beaker Browser.app/Contents/Resources/app/background-process.build.js:3866:5)
    at App.electron.app.on (/Applications/Beaker Browser.app/Contents/Resources/app/background-process.build.js:5586:35)
    at emitTwo (events.js:106:13)
    at App.emit (events.js:194:7)
```

This happened immediately after forking Rotonde. 🤷‍♂️

**Comment by pfrazee** [comment] 2017-10-20 15:04
Ok this is a duplicate of https://github.com/beakerbrowser/beaker/issues/690. Weird bug, I'll look into it. (Closing this one as a duplicate.)

**Closed by pfrazee** 2017-10-20 15:04 UTC
