### ISSUE TITLE
Ctrl+W closes 2 tabs

### ISSUE THREAD

**Issue by hossameldeen** [beakerbrowser/beaker#1175] opened 2018-09-27 07:53 UTC
Operation System: Ubuntu 16.04
Beaker version: Source-latest (8da88a5d80943bb51f408e9cd257d51732dd8716)

- Ctrl+W closes 2 tabs.
- The extra tab closed is the next one, I think.
- Rarely doesn't happen, but most of the time it does.

**Comment by Butterfly** [comment] 2018-09-27 13:07
Hi.. I'm "just" a user out here, but I thought of a question that might help developers understand what's happening. Are the tabs related to each other at all (other than that they're possibly physically side by side) on your screen?

What I mean is... were the tabs originally opened somewhat at the same time, maybe by right clicking then opening tabs down a row of links from one same page?

Or does the behavior seem pretty much random to you?

An example is that I go down a line of links with Gmail in HTML "All Mail" view while on dialup. I can tell that my browsers often consider those newly opened tabs as parent-child/family related because the browser will flip back to what might be considered the next best thing to a parent tab sometimes when I use CTRL+W here. The browser will definitely be somehow methodically working its way down the line of related child tabs even though I otherwise access those tabs to read in extremely random order.

No, I can't say for sure that what I'm seeing on a non-Beaker is about that Preferences choice we have for falling back to last, most recently opened tab when we do CTRL+W. Also just found another Preferences choice that could affect something like this (via Firefox Quantum):

> Ctrl+Tab cycles through tabs in recently used order

That means the browser has a serious consciousness about tracking/documenting that part of our browsing activity. Not hard to imagine that it could be part of a glitch at any point.

Goodness, I hope that somehow makes the same sense here that it does in my head :laughing:

**Comment by pfrazee** [comment] 2018-09-27 16:02
Thanks for reporting. I'll see if I can reproduce.

**Comment by hossameldeen** [comment] 2018-09-28 06:11
@Butterfly Many thanks for trying to help!

I did check the code and I didn't see any relation between them except being side by side. I also did test and by re-arranging tabs; and the extra tab that got closed was the one currently beside it.

Better luck next time :-)

**Comment by pfrazee** [comment] 2018-09-29 01:36
Fixed on master. Thanks for reporting!

**Closed** 2018-09-29 01:36 UTC
Labels: bug

**Comment by hossameldeen** [comment] 2018-09-29 12:32
Checked. Thanks for fixing!
