### ISSUE TITLE
browsing a dat page actually saves it. 

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#322] opened 2017-03-03 12:07 UTC
Operation System: ubuntu 16.10
Beaker Version: latest master

Opening dat://hostless.website/ creates a new archive in `.config/Beaker Browser/Hyperdrive/Archives` without me activating the save button. 

If I click the save-button and then delete the archive from the Library tab it is still there. 

Expected behaviour

 - The UI should tell the truth. 
 - IMO it's OK to cache the site content, but it's not OK, that the "delete" action has absolutely no effect

**Comment by pmario** [comment] 2017-03-03 12:18
What does the "Save Site"  button do?

**Comment by pfrazee** [comment] 2017-03-03 19:50
We haven't implemented the garbage collector yet: https://github.com/beakerbrowser/beaker/issues/144

Until it's implemented, the only effect is to add/remove from your saved sites listing in the library.

**Comment by pfrazee** [comment] 2017-03-07 18:05
I'm going to close, this is basically a duplicate of #144

**Closed by pfrazee** 2017-03-07 18:05 UTC
Labels: discussion
