### ISSUE TITLE
Removing archives from write access menu

### ISSUE THREAD

**Issue by joehand** [beakerbrowser/beaker#265] opened 2017-01-20 20:18 UTC
Operation System: mac osx
Beaker Version: 0.6

* Allow write access to an archive
* Delete the archive from library
* Still is shown in write access for the app

I'd expect an archive to be removed from the "write access" screen after deleting it from my library. This is probably only an issue for developing apps but I have no idea which one is more recent:

<img width="347" alt="screen shot 2017-01-20 at 12 14 37" src="https://cloud.githubusercontent.com/assets/684965/22163974/0a118cd6-df0a-11e6-893d-7485060ba2ce.png">

Is there any way to remove archives from that menu?

These archives are cached anyways, so I can still write to them even if they are "deleted". So It does make sense as implemented but just gets messy if there is no way to remove archives from that menu.

**Comment by pfrazee** [comment] 2017-01-20 21:05
Oh yeah, I've noticed this as well. I've been waiting for more experience with how Dat-based apps will work before solving it.

I'll move it up in the priority queue.

**Comment by pfrazee** [comment] 2017-01-25 22:31
This is a duplicate of https://github.com/beakerbrowser/beaker/issues/193, so I'm going to close

**Closed by pfrazee** 2017-01-25 22:31 UTC
Labels: enhancement
