### ISSUE TITLE
Can't load settings nor devtools

### ISSUE THREAD

**Issue by Gozala** [beakerbrowser/beaker#1476] opened 2019-11-06 18:19 UTC
Operating system: macOS Catalina 10.15

This is:

- [x] a bug
- [ ] general feedback

I can no longer access settings (`beaker://settings`) it just appears as a blank page. It is also impossible to close the tab afterwards.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/21236/68325336-04862180-007e-11ea-8478-913a87cea48b.png">

Any attempt to open any of the devtools also seem to render gray window (although for the brief second I see devtools and then it turns gray). That is a case across working / not working tab devtools and Shell Window shells as well.

<img width="912" alt="image" src="https://user-images.githubusercontent.com/21236/68325507-6777b880-007e-11ea-9404-865e859dd87a.png">
 

I don't know which version of beaker I have (as I was unable to get that info) but I just redownloaded a fresh version from https://beakerbrowser.com/ and it appears to have all the same issues.

I'm suspecting it is something between electron and new macOS as I don't recall any other changes on my system from point were it worked.

**Comment by pfrazee** [comment] 2019-11-06 19:50
Possibly a duplicate of https://github.com/beakerbrowser/beaker/issues/1417

Will get fixed with Beaker Next (though what a pain -- hopefully people will be able to update!)

**Comment by pfrazee** [comment] 2019-11-06 19:50
Thanks for filing

**Comment by no-materials** [comment] 2019-11-19 16:48
> Possibly a duplicate of #1417
> 
> Will get fixed with Beaker Next (though what a pain -- hopefully people will be able to update!)

Greetings! Any rough estimate of Beaker Next's release date? Thanks in advance.

**Comment by Bluebie** [comment] 2019-12-02 05:02
I'm experiencing this issue on Catalina (10.15.1) too. I've also found some Dat websites don't seem to load, and turn in to the same blank white page and tab that cannot be closed. I've checked on another machine running High Sierra (10.13.6) and Beaker's settings open fine on that one, so it looks like this regression maybe specific to Catalina.

**Comment by Bluebie** [comment] 2019-12-02 05:10
Though interestingly, on the High Sierra machine, but not the Catalina machine, I see DNS errors when trying to load the explore page over dat. Works fine over https. Fritter loads fine over dat though. Seems super weird. Confirmed both machines have identical DNS settings and are both connected to the same network router via ethernet. Another weird thing, trying to take a screenshot of the browser on the High Sierra machine resulted in a blank white window in the screenshot. To take this shot, I had to VNC in via Apple Screen Sharing and take the snapshot on the host machine by screenshotting the VNC client. (which is also why there are jpeg-like artefacts in this png)

![Screen Shot 2019-12-02 at 4 09 26 pm](https://user-images.githubusercontent.com/12768/69932170-1e504280-151e-11ea-8cfe-277c8a376960.png)

**Comment by pfrazee** [comment] 2019-12-02 16:05
> Greetings! Any rough estimate of Beaker Next's release date? Thanks in advance.

Unfortunately no. We publish regular updates at https://twitter.com/beakerbrowser

**Comment by holtwick** [comment] 2020-02-04 12:49
Still seeing this problem here with Beaker 0.8.8 and macOS 10.15.3. Beaker also creates some output in console logs, maybe related:

![Console 2020-02-04 at 13 48 50@2x](https://user-images.githubusercontent.com/49557/73746271-1a76b180-4755-11ea-9489-ce44987cd7af.png)

**Closed** 2020-05-06 16:29 UTC
Labels: bug, duplicate
