### ISSUE TITLE
mp4 videos don't seem to render over Dat

### ISSUE THREAD

**Issue by rh0** [beakerbrowser/beaker#751] opened 2017-11-12 01:53 UTC
Operation System: _Arch Linux_
Beaker Version: _Version: 0.7.7 Electron: 1.8.2 - Chromium: 59.0.3071.115 - Node: 8.2.1_

---
I just published a blog post in which I included some video tags using mp4. Initially Beaker would crash when trying to load the page.  I pulled the latest from master and rebuilt Beaker.  It will now load the page, but the mp4's appear to be blank.  I believe my markup is correct and have checked the https version in FF and Chrome both of which render fine. Out of curiosity I checked the https version Beaker and strangely it also renders fine.  This seems to only occur when accessing the page via Dat.  Searching the issue queues the only mentions of problems with video I could find were related to filesize, however both of these mp4's are quite small (< 3mb).

#### The offending page can be found at:
+ dat://electro.pizza/2017/11/punch-python-serial/
+ https://electro.pizza/2017/11/punch-python-serial/

After a bit more diggin around I found that if I access the mp4 directly, beaker will initially not render the file.  However if I hit the back button, then jump back forward, the video plays just fine.
dat://electro.pizza/2017/11/punch-python-serial/punch-serial-demo.mp4

**Comment by pfrazee** [comment] 2017-11-12 17:17
The crash was caused by https://github.com/beakerbrowser/beaker/issues/474. We have a fix landed and we're trying to get the new version out soon. (There are still a few upstream deps which need to be updated.)

I'm going to close this issue in case the new version solves it. If you still find video's *dont render*, that's a separate issue, and we'll need to reopen.

**Closed by pfrazee** 2017-11-12 17:17 UTC
