### ISSUE TITLE
JS error on startup

### ISSUE THREAD

**Issue by xpollen8** [beakerbrowser/beaker#464] opened 2017-05-26 02:25 UTC
Operation System: OSX 10.10.5
Beaker Version: 0.7.0

Installed over the top of 0.6.1, get this when trying to start
<img width="408" alt="untitled" src="https://cloud.githubusercontent.com/assets/552254/26478256/dbb1756c-417f-11e7-90d4-a0364dfdc035.png">

**Comment by pfrazee** [comment] 2017-05-26 02:31
Ok, how did you install the new version? Was it from source, the prebuilt
binary, or the auto-updater? If it was by source, try running `npm run
burnthemall`

**Comment by xpollen8** [comment] 2017-05-26 02:42
binary download.

(where's a download of 0.6.1 hiding, in the meantime?)

**Comment by pfrazee** [comment] 2017-05-26 02:55
Unfortunately you wouldnt want to use 0.6.1; its Dat protocol is deprecated and not compatible with anything now.

Try uninstalling and reinstalling Beaker 0.7. In the meantime, I'll try downloading and installing from scratch to see if I can't reproduce the error.

**Comment by xpollen8** [comment] 2017-05-26 03:04
Same outcome, the warning pasted above.

**Comment by pfrazee** [comment] 2017-05-26 03:11
Hmm. I just gave it a shot and couldn't reproduce. Could you try using one of the two commands below, depending on the one you prefer (MacPorts or Homebrew)

```
sudo port install libsodium
```

```
brew install libsodium
```

**Comment by xpollen8** [comment] 2017-05-26 03:38
Same outcome. Keep in mind, I'm running 10.10.5, here.

**Comment by pfrazee** [comment] 2017-05-26 03:41
Yeah, 10.10.5 *could* be the problem but that's not ideal! You could try building from source if you're interested.

When he's back online, I'll ask the sodium-native maintainer if he has any ideas.

**Comment by pfrazee** [comment] 2017-05-26 15:05
https://github.com/codeforscience/sciencefair/issues/62 This same issue was reported on a project run by the team that maintains sodium-native (and Dat). So, it's not just you.

**Comment by Yuffster** [comment] 2017-06-09 03:40
I got the same error and `brew update libsodium` did the trick for me.  Also on 10.10.5.

**Comment by pfrazee** [comment] 2017-06-09 14:57
@Yuffster you rock. @xpollen8 can you give that a shot and lmk if it's solved?

**Comment by mafintosh** [comment] 2017-06-09 15:08
Hmm, `brew install` should *not* be nessesary.
Can someone experiencing this issue try this out for me and report the output

```
cd /Applications/Beaker Browser.app/Contents/Resources/app/node_modules/sodium-native/prebuilds/darwin-x64

echo 'electron 54 links'
otool -L electron-54.node

echo 'libsodium links'
otool -L libsodium.dylib
```

**Comment by mafintosh** [comment] 2017-06-09 15:10
@Yuffster did you have libsodium installed through brew before trying Beaker by any chance?

**Comment by xpollen8** [comment] 2017-06-09 15:46
electron-54.node:
	@loader_path/libsodium.dylib (compatibility version 21.0.0, current version 21.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.5.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.51.1)
  
libsodium.dylib:
	@loader_path/libsodium.dylib (compatibility version 21.0.0, current version 21.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.51.1)

also - the brew install of libsodium made no change in startup behavior

**Comment by pfrazee** [comment] 2017-06-09 15:48
:( oh well

**Comment by mafintosh** [comment] 2017-06-09 15:53
@xpollen8 if you open `node` and do `require('sodium-native')` from that folder, what happens?

**Comment by pfrazee** [comment] 2017-06-09 15:58
https://gist.github.com/pfrazee/6b3b80b668cb310a3f0cf75101f742e0

**Comment by Yuffster** [comment] 2017-06-09 22:44
@mafintosh Yeah, but I can't for the life of me remember which version.  Installed it maybe two years ago.

**Comment by pfrazee** [comment] 2017-07-20 20:22
Closing because I believe maf fixed this upstream.

**Closed by pfrazee** 2017-07-20 20:22 UTC
Labels: bug
