### ISSUE TITLE
"See What Others Have Built" results in Page Not Found

### ISSUE THREAD

**Issue by canadaduane** [beakerbrowser/beaker#1397] opened 2019-04-25 21:12 UTC
Operation System: Mac OS 10.14.4
Beaker version: 0.8.7

When using Beaker for the first time, the `Get started` page has a "See what others have built" link. I clicked the link and it went to `dat://explore.beakerbrowser.com/` which resulted in a 404:

![image](https://user-images.githubusercontent.com/129/56768786-7c3cd080-676c-11e9-8df0-b363cbc8a50f.png)

**Comment by pfrazee** [comment] 2019-04-26 16:14
Thanks for filing, I'll check into this.

**Comment by pfrazee** [comment] 2019-04-26 17:25
Oh right, this is a duplicate of https://github.com/beakerbrowser/beaker/issues/1376. I'll get the fix release out soon.

**Closed by pfrazee** 2019-04-26 17:25 UTC
Labels: bug
