### ISSUE TITLE
Settings page is blank

### ISSUE THREAD

**Issue by guyjames** [beakerbrowser/beaker#1084] opened 2018-07-19 08:34 UTC
Operation System: Ubuntu 18.04
Beaker version: 0.8 beta

beaker://settings/ returns a blank white page. I have tried reloading multiple times but no change.

**Comment by pfrazee** [comment] 2018-07-19 15:51
Hmm. Do you know how to open devtools? If so, could you do so and check if there are any errors in the console?

**Comment by matt1** [comment] 2018-08-02 14:42
I also had the same issue when building from source on Debian.  Curiously, I *dont* get this when doing a remote connection into my Debian machine, only when using it directly - remote connections use Cinnamon window manager, but direct connections use KDE Photon window manager.

Error in the console was this:

```
> Uncaught (in promise) Error: Command failed: xdg-mime query default "x-scheme-handler/dat"
> 
>     at setup (main.js:739)
>     at <anonymous>
```

This is caused by the call to

> ` defaultProtocolSettings = await beaker.browser.getDefaultProtocolSettings();`

That calls into this: https://github.com/beakerbrowser/beaker/blob/a6ce16c7af367cf57eb7b3afa06c7f982ae53dda/app/background-process/browser.js#L200

I tried to attach a debugger to the background process (node --inspect tasks/start-cli.js then using chrome dev tools) but no breakpoints would fire.

If you can advise best way to debug the background process I can dig deeper into this.

**Comment by matt1** [comment] 2018-08-02 15:18
Looks like this is just the exec promise failing without a safe default, causing the Promise.all to fail.   Added some safe defaults in a PR.

**Comment by pfrazee** [comment] 2018-08-04 16:46
@matt1 Appreciate that, merged. I suppose that means you wont be able to register the default browser handling.

**Comment by cotg1776** [comment] 2018-08-19 13:03
I ran into this same issue. It seems I've fixed the issue by going to the System Settings, in Linux Mint 18 btw, and setting the default browser to the *.AppImage of Beaker that I run. Also I believe I clicked "Yes" in the dialog box that pops up when asked to install the application to the application menu, etc. which happens at initial running.

**Comment by pfrazee** [comment] 2018-08-19 17:04
I'm going to close as the initial issue was solved, and open a followup

**Closed by pfrazee** 2018-08-19 17:04 UTC
Labels: bug
