### ISSUE TITLE
libsodium.dylib issue

### ISSUE THREAD

**Issue by maxogden** [beakerbrowser/beaker#548] opened 2017-06-19 21:02 UTC
Operation System: Mac 10.10 Yosemite
Beaker Version: Beaker Browser 0.7.2.dmg

Moved app from DMG into /Applications. Double clicked and got this:

<img width="532" alt="screen shot 2017-06-19 at 2 00 18 pm" src="https://user-images.githubusercontent.com/39759/27305758-d3df4446-54f7-11e7-9bf2-c8f17c3c751b.png">

**Comment by maxogden** [comment] 2017-06-19 21:05
Ah, I think its the same issue as https://github.com/codeforscience/sciencefair/issues/62, basically @mafintosh's fault :) I guess Dat only supports mac OS > 10.12 or something now?

**Comment by pfrazee** [comment] 2017-06-20 14:40
Yeah this is a duplicate of https://github.com/beakerbrowser/beaker/issues/464 too. I'm waiting for maf to handle it

**Closed by pfrazee** 2017-06-20 14:40 UTC
