### ISSUE TITLE
Browser inconsitency for big sites

### ISSUE THREAD

**Issue by frankiezafe** [beakerbrowser/beaker#1239] opened 2018-11-02 16:40 UTC
Operation System: Linux Mint 18.2 cinnamon 64bits - kernel 4.8.0-53-generic
Beaker version: 0.8.0-x86_64 via AppImage

I'm mirroring my personal website via httrack: it is currently < 900MB and > 8800 files - the browser becomes very slow and tends to crash when i'm going to library and try to updates my website -> dat://69136283f6bfc7fe07ac3b94675b161a7d1be7db6690ceb6e3c6599a6d06f065

update: worst than before: the error is now "archive not found", even if files are still there

**Comment by pfrazee** [comment] 2018-11-02 21:07
@frankiezafe yeah this is a known issue. We're working on some updates to Dat itself which will improve performance. The "Archive not found" is a misinterpretation of a timeout -- I'm going to fix that in a bit.

Closing as a duplicate of https://github.com/beakerbrowser/beaker/issues/1169.

**Closed by pfrazee** 2018-11-02 21:07 UTC
