### ISSUE TITLE
audio files not uploading properly?

### ISSUE THREAD

**Issue by xDekpix** [beakerbrowser/beaker#1609] opened 2020-05-16 17:13 UTC
i actually noticed this on the previous version of beaker, but assumed it'd be fixed with the update.
audio files had worked at one point, and i would share them as i would any other file, but at some point even before beaker beta, audio files would only show as having 0:00 time on them and became unplayable. i'm not sure if the audio files arent uploading at all because you can't download them if they won't load, or if they just aren't displaying properly in the browser.

-upload an audio file to hyperdrive
-try to view the file source.
-audio file loads as an empty file, says that the time of the file is 0:00-0:00 and is unplayable and can't be saved to desktop.

**Expected behavior**
audio file is supposed to be able to be viewable and if it loads you should be able to save a copy to your desktop.

i can get around it by packaging them as a .rar and letting them be downloadable that way, but being unable to upload audio files as a source will also cause issues trying to embed them.
idk if anybody remembers, but there were a couple sites, like the back to the 80s dat site in the previous version of beaker browser, that had previously worked, but the audio cut out when the audio source files stopped working.

![image](https://user-images.githubusercontent.com/36095003/82125862-d2fdb980-9776-11ea-9ffc-fe358a3776a7.png)

**Comment by Foldover** [comment] 2020-05-16 17:20
I noticed that too, been too lazy to report though ha! For what it is worth, you can get around this and embed via Javascript while the issue is investigated. Something like:

```js
const soundBuffer = await beaker.hyperdrive.readFile('/path-to-file/audio.wav', 'binary');
const blob = new Blob([soundBuffer], { type: 'audio/wav' });
document.querySelector('audio').src = URL.createObjectURL(blob);
```

**Comment by pfrazee** [comment] 2020-05-16 17:43
Known issue! It requires a patch to Chromium which they didn't want to upstream, but thankfully Electron has worked with me on a solution that's awaiting final review (https://github.com/electron/electron/pull/22955). @Foldover's solution does work for the moment.

Closing as duplicate of https://github.com/beakerbrowser/beaker/issues/1560

**Closed by pfrazee** 2020-05-16 17:43 UTC
Labels: bug
