### ISSUE TITLE
0.7.10 `npm run release` fails on linux

### ISSUE THREAD

**Issue by jeancf** [beakerbrowser/beaker#793] opened 2017-12-19 21:31 UTC
I am trying to build beaker for packaging on linux. `npm install` works fine but `npm run release` (which I assume creates an executable package) fails with the following trace:

Operation System: linux 4.14.5-1
Beaker Version: 0.7.10
```
$ npm run release

> beakerbrowser@ release /home/jeancf/Desktop/beaker-0.7.10
> npm run build && build -p never && gulp postbuild


> beakerbrowser@ build /home/jeancf/Desktop/beaker-0.7.10
> gulp build

[20:47:31] Using gulpfile ~/Desktop/beaker-0.7.10/gulpfile.js
[20:47:31] Starting 'burnthemall-maybe'...
[20:47:31] Finished 'burnthemall-maybe' after 6.12 ms
[20:47:31] Starting 'bundle'...
[20:47:31] Starting 'less'...
[20:47:31] Finished 'less' after 40 ms
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'default' is imported from external module 'function-queue' but never used
'default' is imported from external module 'moment' but never used
[20:47:40] Finished 'bundle' after 8.99 s
[20:47:40] Starting 'build'...
[20:47:40] Finished 'build' after 75 μs
electron-builder 19.43.4
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for linux x64 using electron 1.8.2-beta.2 to dist/linux-unpacked
Error: ENOENT: no such file or directory, open '/home/jeancf/Desktop/beaker-0.7.10/app/node_modules/sodium-signatures/node_modules/sodium-native/tmp/lib/libsodium.so'
    at w (/home/jeancf/Desktop/beaker-0.7.10/node_modules/electron-builder/src/asar/asarUtil.ts:191:11)
    at writeStream.write (/home/jeancf/Desktop/beaker-0.7.10/node_modules/electron-builder/src/asar/asarUtil.ts:193:43)
    at afterWrite (_stream_writable.js:466:3)
    at onwrite (_stream_writable.js:457:7)
    at fs.write (fs.js:2242:5)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:703:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! beakerbrowser@ release: `npm run build && build -p never && gulp postbuild`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the beakerbrowser@ release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jeancf/.npm/_logs/2017-12-19T19_47_59_728Z-debug.log
```

Am I on the right track to build a package? How can I fix the error?

**Comment by Butterfly** [comment] 2017-12-20 00:28
Hi.. Am mostly still a newbie here, but occasionally I can still catch something. For this line:

> Error: ENOENT: no such file or directory, open '/home/jeancf/Desktop/beaker-0.7.10/app/node_modules/sodium-signatures/node_modules/sodium-native/tmp/lib/libsodium.so'

That `ENOENT` could be seen as meaning something like "error: no entity (or entry)".

Can you follow your file hierarchy and locate that `libsodium.so` file manually? If it's really not at that location above, you could try to run something like `updatedb` and then `locate libsodium.so` to see where that file landed within your Linux file hierarchy, if it's even there in your setup at all.

At this point in things, users over at the npm/npm Github tend to have success by doing things like cleaning and/or updating their cache. Some users have even gone the harsh route of deleting something, like maybe a full directory of some sort, but I'm not comfortable with that route... so I'm not going to even try to search that one down. I think what happens when users go that hardcore deletion route is they're simply resetting whatever they did the first time.

**Comment by pfrazee** [comment] 2017-12-20 16:59
@jeancf Could you try running `npm run burnthemall` and then `npm run release` ?

**Comment by jeancf** [comment] 2017-12-21 16:19
@pfrazee `npm release` still fails with the same error after trying `npm run burnthemall`.

Following the idea from @Butterfly I was able to locate the issue though.
`/home/jeancf/Desktop/beaker-0.7.10/app/node_modules/sodium-signatures/node_modules/sodium-native/tmp/lib/libsodium.so` is actually a broken symlink.

```
-rw-r--r-- 1 jeancf jeancf 2.3M Dec 21 17:05 libsodium.a
-rwxr-xr-x 1 jeancf jeancf 1.1K Dec 21 17:05 libsodium.la
lrwxrwxrwx 1 jeancf jeancf   19 Dec 21 17:05 libsodium.so -> libsodium.so.18.2.0
lrwxrwxrwx 1 jeancf jeancf   19 Dec 21 17:05 libsodium.so.18 -> libsodium.so.18.2.0
drwxr-xr-x 2 jeancf jeancf 4.0K Dec 21 17:05 pkgconfig
```
There is a `/home/jeancf/Desktop/beaker-0.7.10/app/node_modules/sodium-signatures/node_modules/sodium-native/deps/libsodium/src/libsodium/.libs/libsodium.so.18.2.0` however. If I copy that file to the other directory the symlinks are OK again.

Now running `npm run release` fails with another error:

```
> beakerbrowser@ release /home/jeancf/Desktop/beaker-0.7.10
> npm run build && build -p never && gulp postbuild


> beakerbrowser@ build /home/jeancf/Desktop/beaker-0.7.10
> gulp build

[17:13:39] Using gulpfile ~/Desktop/beaker-0.7.10/gulpfile.js
[17:13:39] Starting 'burnthemall-maybe'...
[17:13:39] Finished 'burnthemall-maybe' after 467 μs
[17:13:39] Starting 'bundle'...
[17:13:39] Starting 'less'...
[17:13:39] Finished 'less' after 8.66 ms
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'TimeoutError' is imported from external module 'beaker-error-constants' but never used
'default' is imported from external module 'function-queue' but never used
'default' is imported from external module 'moment' but never used
[17:13:42] Finished 'bundle' after 3.3 s
[17:13:42] Starting 'build'...
[17:13:42] Finished 'build' after 22 μs
electron-builder 19.43.4
Skip app dependencies rebuild because npmRebuild is set to false
Packaging for linux x64 using electron 1.8.2-beta.2 to dist/linux-unpacked
Building AppImage for arch x64
Error: Cannot detect repository by .git/config. Please specify "repository" in the package.json (https://docs.npmjs.com/files/package.json#repository).
Please see https://electron.build/configuration/publish
(...)
```

**Comment by pfrazee** [comment] 2017-12-21 17:17
@jeancf what distro are you running?

**Comment by chartgerink** [comment] 2017-12-21 17:29
For me starting Beaker fails with `npm run release` and succeeds as intended with `npm start`. Don't know whether that matters but just posting as FYI.

```bash
Error: ENOENT: no such file or directory, open '/home/chjh/beaker/app/node_modules/sodium-signatures/node_modules/sodium-native/tmp/lib/libsodium.so'
    at w (/home/chjh/beaker/node_modules/electron-builder/src/asar/asarUtil.ts:191:11)
    at writeStream.write (/home/chjh/beaker/node_modules/electron-builder/src/asar/asarUtil.ts:193:43)
    at afterWrite (_stream_writable.js:455:3)
    at onwrite (_stream_writable.js:446:7)
    at fs.js:2246:5
    at FSReqWrap.wrapper [as oncomplete] (fs.js:703:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! beakerbrowser@ release: `npm run build && build -p never && gulp postbuild`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the beakerbrowser@ release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chjh/.npm/_logs/2017-12-21T17_28_20_525Z-debug.log
```

**Comment by jeancf** [comment] 2017-12-21 17:32
I am on Arch Linux.

/~JC


-------- Message original --------
Objet : Re: [beakerbrowser/beaker] 0.7.10 `npm run release` fails on linux (#793)
De : Paul Frazee <notifications@github.com>
À : beakerbrowser/beaker <beaker@noreply.github.com>
Cc : JC Francois <jc@noirextreme.com>,Mention <mention@noreply.github.com>

**Comment by pfrazee** [comment] 2017-12-22 01:13
This seems like an issue either with an upstream dependency or with NPM. What version of node/NPM are you using?

**Comment by jeancf** [comment] 2017-12-22 08:07
node-9.3.0
npm-5.6.0

Sorry, I am unfamiliar with npm and how it works. Is appImage part of npm?  Do you imply that when it npm tries to build AppImage, it is actually trying to installl it to my system and not inside the beaker folder? I looked for an appimage package in the repos but there is none.

**Comment by pfrazee** [comment] 2017-12-31 19:18
@jeancf is your goal to build a distributable package of Beaker, or just to build it so you can run from source? If it's the latter, then you don't need to run `npm run release`. You can just do `npm install ; npm run rebuild; npm start`. And then for subsequent runs, `npm start`

**Comment by jeancf** [comment] 2018-01-01 15:17
@pfrazee I was trying to build a distributable package for arch. I was hoping that `npm run release` would generate the files in the target system locations ('/usr/share', '/usr/bin', etc.) before packaging them in the `AppImage` file (disclaimer: I have no idea whether this is how AppImageKit works).

In the meantime I noticed that somebody created [a package for arch](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=beakerbrowser) invoking `npm install`and `npm run rebuild`.

On second thoughts I would be happy with a package that is just installing the AppImage file system wide. However for that there is an issue with the install window that pops up when you launch the AppImage:

> Would you like to integrate /home/jeancf/Desktop/beaker-browser-0.7.10-x86_64.AppImage with your system?
> 
>  This will add it to your applications menu and install icons.
> If you don't do this you can still launch the application by double-clicking on the AppImage.

Is there a way to suppress this message (e.g. by passing a command-line argument such as `./beaker-browser-0.7.10-x86_64.AppImage --no-install`)? If it was the case the package could handle the placement of icons and desktop files in system-wide locations instead of `~/.local`

**Comment by pfrazee** [comment] 2018-01-02 18:56
Try setting the env var `APPIMAGE_SILENT_INSTALL=1`

**Comment by jeancf** [comment] 2018-01-03 15:46
@pfrazee Thanks. with `APPIMAGE_SILENT_INSTALL=1` the popup window does not appear but the installation does take place anyway. As a workaround [my package](https://aur.archlinux.org/packages/beaker-browser-bin/) is launching the AppImage from a bash script that deletes the installed files in .local when the app exits.

I also read that creating a `$HOME/.local/share/appimagekit/no_desktopintegration` file could be a solution. I will look into it.

**Comment by pfrazee** [comment] 2018-01-03 17:02
Ok cool. I know the electron-builder has been developing its app image tools a lot lately. It might still need some work.

**Comment by jeancf** [comment] 2018-01-04 13:29
For reference:

* Adding `~/.local/share/appimagekit/no_desktopintegration` disables installation of AppImage for current user
Adding `/usr/local/share/appimagekit/no_desktopintegration` disables installation of AppImage for all users

**Closed** 2020-05-06 16:10 UTC
Labels: bug, linux
