### ISSUE TITLE
Beaker remains open in the background when closed

### ISSUE THREAD

**Issue by DTV96Calibre** [beakerbrowser/beaker#893] opened 2018-03-17 21:57 UTC
Operation System: Windows 10
Beaker version: v0.8.0-prerelease.3
![image](https://user-images.githubusercontent.com/10363350/37560278-b8faec0e-2a0b-11e8-81df-eb777362981a.png)
The above processes appear under "Background processes" after closing Beaker and disappear after opening Beaker. Using npm start to launch a different version of Beaker gets hijacked by the existing processes and any changes you might have been trying to test aren't loaded.

It's widely considered bad behavior for a program to remain open in the background when closed with window decorations so if this is intentional, it ought to be changed and made optional.

**Comment by taravancil** [comment] 2018-03-17 22:13
We actually removed the behavior that keeps Beaker running in the background in 0.8, so I think what you're seeing is the 0.7 background process still active, and thus interfering with the new process you're trying to start.

Kill the background process and try again, and let us know if you continue to have trouble.

**Comment by DTV96Calibre** [comment] 2018-03-17 22:27
Restarted my system for good measure and the problem persists.

**Comment by DTV96Calibre** [comment] 2018-03-17 22:31
Uninstalling and installing the latest beta release directly doesn't resolve this either.

**Comment by taravancil** [comment] 2018-03-17 23:16
Hm, that's odd. We definitely took out the background process code in 0.8, but we'll look into it to see if we can figure out what's going on.

**Comment by pfrazee** [comment] 2018-03-21 10:42
Yep I just confirmed this is happening. 🤦‍♂️ 

I think it's because of a piece I removed in https://github.com/beakerbrowser/beaker/commit/5014bf7ef6c867c7dcef56624e5111338b3b99b8. The `'window-all-closed'` event needs to be handled and we probably aren't currently.

**Comment by pfrazee** [comment] 2018-03-21 15:42
A fix is committed, we'll need to test on windows before we close.

**Comment by DTV96Calibre** [comment] 2018-03-21 18:33
I've tested it on Windows 10 by building with `yarn run release` and running the executable in the unpacked folder and it looks like it's fixed.

**Comment by taravancil** [comment] 2018-03-21 18:46
Nice! Thanks @DTV96Calibre for reporting and testing.

**Closed by taravancil** 2018-03-21 18:46 UTC
Labels: bug
