### ISSUE TITLE
Shortcut CMD A 

### ISSUE THREAD

**Issue by maxlamenax** [beakerbrowser/beaker#733] opened 2017-10-30 20:33 UTC
Operation System: OSX El Capitan
Beaker Version:Beaker v0.7.7 is up-to-date 

when pressing the short cut cmd a for select all it close the app 
i am french and use an azerty keyboard its very anoying

**Comment by vsivsi** [comment] 2017-10-30 21:19
@maxlamenax   I just updated to v0.7.7 and tried this (cmd-a in both the URL bar and rendered text) and I don't observe what you describe.  You should probably add more precise detailed instructions for reproducing the bug you are seeing.

**Comment by maxlamenax** [comment] 2017-10-30 21:26
i am sorry i am dont speak english but its simple, il all my other apps i use CMD A tou select all text or link in the adress bar i use it very often, in the Beaker app when i o the CMD A shortcut it close the app... and its not  mistake from me, it make the same action as cmd Q  ...

**Comment by vsivsi** [comment] 2017-10-30 21:32
I see, is that because the `A` key on your AZERTY keyboard is in the position of the `Q` key on an English langauge keyboard?  Does hitting `cmd-Q` on your keyboard have the effect of "select all"?

**Comment by maxlamenax** [comment] 2017-10-30 21:33
non CMD q make the app quit too

**Comment by maxlamenax** [comment] 2017-10-30 21:33
i looking for a screen recorder right now to make a demo

**Comment by vsivsi** [comment] 2017-10-30 21:36
On a mac you can use the built in Quicktime Player app to make a recording... 

`File... > New Screen Recording` (in English)

**Comment by maxlamenax** [comment] 2017-10-30 21:40
thanks https://youtu.be/seqFRjkEMJA

**Comment by maxlamenax** [comment] 2017-10-30 22:02
the CMD Z shortcut wont work too it close the tab instead of undo... for the moment i will stop use the app too much bug

**Comment by pfrazee** [comment] 2017-10-31 02:54
Thanks @vsivsi for helping debug.

@maxlamenax I'll look into it. Since you clearly have no issue with Hyper.is, I can at least compare my code to theirs.

**Comment by pfrazee** [comment] 2017-10-31 19:28
A fix has been landed in master. We'll include it in the next release.

**Closed** 2017-10-31 19:28 UTC
Labels: bug
