### ISSUE TITLE
ctrl-click a link opens and activates the new tab

### ISSUE THREAD

**Issue by pmario** [beakerbrowser/beaker#321] opened 2017-03-03 11:00 UTC
Operation System: ubuntu 16.10
Beaker Version: 0.6.1 - master: 9d3f1037f075cac0ac54b3d5ce44da0098288ba3

Exptected:

 - Ctrl-click a link should open a new tab, but focus should stay at current tab, to make the experience consistent with other browsers. 

To reproduce the issue: 

 - open: dat://hostless.website/
 - ctrl-click Beaker Docs - https://beakerbrowser.com/docs
   - new tab opens, and is selected -> issue
 - ctrl-click the first link: dat://paulfrazee.com
   - new tab opens and it is selected -> issue!

**Comment by pfrazee** [comment] 2017-03-03 19:51
This is a duplicate of https://github.com/beakerbrowser/beaker/issues/291, closing

**Closed by pfrazee** 2017-03-03 19:51 UTC

**Comment by pmario** [comment] 2017-03-03 20:26
ah. .. ok. .. really :) "No description provided."
