### ISSUE TITLE
Main thread crashes immediately

### ISSUE THREAD

**Issue by rickycodes** [beakerbrowser/beaker#707] opened 2017-10-17 01:57 UTC
Operation System: OSX Yosemite version 10.10.5
Beaker Version: Latest (Beaker v0.7.5)

Just installed Beaker and as soon as I attempt to visit anything I get an "Uncaught Exception Error":

![beaker](https://user-images.githubusercontent.com/675259/31643156-efa4220a-b2bc-11e7-93e5-d276a12243e3.gif)

![image](https://user-images.githubusercontent.com/675259/31643140-d02b741e-b2bc-11e7-89c4-76dbf2f90d0e.png)

**Comment by pfrazee** [comment] 2017-10-17 02:01
Yeah, sorry, this is a known bug that hits some people. We're releasing a new version tomorrow with a fix. If you build from source, it should work for you.

Closing as a duplicate of https://github.com/beakerbrowser/beaker/issues/698.

**Closed by pfrazee** 2017-10-17 02:01 UTC

**Comment by rickycodes** [comment] 2017-10-17 02:46
@pfrazee no worries! I had tried searching to see if this was a dupe

thanks, i will attempt building from source for now

**Comment by rickycodes** [comment] 2017-10-17 19:57
@pfrazee fwiw this is indeed fixed for me when I build from source

thanks again

**Comment by pfrazee** [comment] 2017-10-17 20:17
👍
