### ISSUE TITLE
"Show tabs from last session" doesn't work

### ISSUE THREAD

**Issue by jeremyredhead** [beakerbrowser/beaker#1324] opened 2019-01-20 23:28 UTC
Operation System: Windows 7 64-bit
Beaker version: 0.8.2

Problem: Tabs from the last session aren't getting restored.
Steps to Reproduce: Open beaker, and then some websites in tabs. Close Beaker and re-open.

**Comment by pfrazee** [comment] 2019-01-21 20:38
Just to make sure, did you have that setting enabled?

**Comment by jeremyredhead** [comment] 2019-01-22 18:43
Dang, I felt like something was missing from my bug report!

Anyway, yes. I'd even tried turning the setting "off & on" again before testing :P

**Comment by da2x** [comment] 2019-01-26 06:10
This is probably a duplicate of #1280.

**Comment by ThisIsMissEm** [comment] 2019-02-20 18:35
@pfrazee it seems if you restart beaker before it's actually started, then you can lose the last open tabs (because something's already overwritten them) — just had this happen to me when I accidentally quit beaker as it was opening whilst trying to quit a different application

**Comment by Butterfly** [comment] 2019-02-20 21:35
> it seems if you restart beaker before it's actually started, then you can lose the last open tabs (because something's already overwritten them) — just had this happen to me when I accidentally quit beaker as it was opening whilst trying to quit a different application

The good news is: Ditto on that for me with the "good news" being that my experiences were with at least two other of the better known browsers that have been around for years. **It's not just a Beaker thing.** :champagne: 

My instances were the exact same kind of circumstance where browsers were taking their sweet time loading up. Meanwhile, I hit "CTRL+Q" or "CTRL+SHIFT+W" to close some other unrelated package/program JUST as those browsers were visibly coming to Life > *ZAP!*

There have been one-off backups (e.g. dot bak files) that I've been able to use to *attempt* to recover those lost tabs... and sometimes even lost bookmarks. That doesn't always work, e.g. those are GONE if you open and close twice before you remember to stop and make a config files backup before taking one more step forward. The recovery process can be a real pain even when you have half a clue what you're doing. :laughing:

**Comment by ThisIsMissEm** [comment] 2019-02-20 23:02
I think the way to solve this is to change SessionWatcher to be initialized with the tabs from the stored file, even if those tabs aren't yet open. Or to change how you interact with SessionWatcher, as to not install the on-exit handler until the session has been restored. Likewise, the restoration of a session should be awaitable, as otherwise you don't know when you've finished restoring the session

**Comment by Butterfly** [comment] 2019-02-21 00:12
> I think the way to solve this is to change SessionWatcher to be initialized with the tabs from the stored file, even if those tabs aren't yet open. **Or to change how you interact with SessionWatcher, as to not install the on-exit handler until the session has been restored.**

That last part right there, that's about what I was thinking... Tell it to just stand by for a few extra seconds until all that has loaded, has settled in and registered fully new, fresh session backup files (based on previous session files) **THEN** exit even though it might be an accidental shutdown k/t something like an ill-timed "CTRL+Q" or what-have-you.

And I was thinking... if this is still an issue for other browsers, this would get Beaker some new page views if that tweak worked and then became common knowledge elsewhere for this [genre] of software packages.. Cool! :smile:

**Comment by ThisIsMissEm** [comment] 2019-02-21 13:59
I think you can allow the exit straight away & just not write a new session that's empty if the old one didn't properly restore.

**Closed** 2020-05-06 16:26 UTC
Labels: bug
