### ISSUE TITLE
Add a configurable cap on Dat bandwidth use

### ISSUE THREAD

**Issue by gojomo** [beakerbrowser/beaker#757] opened 2017-11-14 21:13 UTC
Operation System: MacOS Sierra
Beaker Version: v0.7.7

Using Beaker (in MacOS guest VM under MacOS VMWare Fusion host) on home wifi network with asymmetric, small-upload-bandwidth internet connection (ADSL). 

When Beaker is running with a few `dat:` tabs open, internet usability collapses in guest VM where Beaker is running, in host VM, and other devices sharing same internet uplink. (That is: lots of loading-slowly, failed-to-connect, etc. Google Wifi app even has problems connecting reliably to Google OnHub.) I strongly suspect uplink-saturation (perhaps exacerbated by UDP/multicast?) is sabotaging other connections – an effect really common in P2P file-sharing apps that don't self-limit (via a manual cap or adaptive backoff) their uplink saturation. 

Do any parts of the Beaker Browser stack have a hidden option to limit uplink bandwidth? Can it be added? 

Is the DAT-P2P-Swarm background traffic all on a few stable ports suitable for the external application of OS/appliance shaping/QoS rules?

**Comment by pfrazee** [comment] 2017-11-15 03:04
Hey @gojomo.

We don't have any config for this yet but it'd be wise to do. @mafintosh do you have any thoughts on how we might implement a hard cap on bytes per second? I'm sure you use backpressure in your replication streams; I bet we could add a transform to each replication stream that monitors total usage and chokes down the streams. That would then leave the discovery-swarm, and I think we'd need to dig into that code a bit first.

@gojomo while Dat *could* be saturating the uplink, I haven't personally observed that yet with pretty heavy usage. Is the VM or the machine resource limited? I wonder if you might be experiencing an edge case, or if something unrelated to dat could be the cause. We should poke at that a bit; it might need to be something we address separately.

**Comment by pfrazee** [comment] 2017-11-15 03:04
I hope you don't mind, I retitled the issue

**Comment by gojomo** [comment] 2017-11-15 18:11
It may be aggravated by something else about my setup, in particular the MacOS guest-VM on MacOS-host, or something specific to my Google OnHub/DSL-modem/ISP. 

But the rash of connection failures in the guest, host, and other devices sharing the same uplin, immediately remedies when Beaker Browser is quit, and gradually reoccurs when Beaker is re-launched with a bunch of `dat:` tabs open and a high peer count. I notice that Beaker in an otherwise 'idle' state (with-regard-to user-initiated actions) has a significant and largely symmetric send/receive network usage, and based on seeing similar side-effects with other apps that max the uplink strongly suspect that's the root cause. 

Which protocols/ports are used by the P2P DAT protocols? (Despite the copious JS-API-level docs for DAT stuff, having a hard time finding specs on which network protocols/ports used.)

**Comment by gojomo** [comment] 2017-11-15 18:17
Note that while there could be good reasons for a receive/downlink cap as well, the specific kind of interference-of-other-connections that happens on these asymmetric links can be remedied with a send/uplink/outbound cap, leaving receive/downlink/inbound traffic uncapped. (So a single cap wouldn't be the best fix.)

**Comment by pfrazee** [comment] 2017-11-16 15:14
Ok, we'll look into getting a cap in soon. I noticed a few performance problems with heavy dat usage yesterday, so I'm going to investigate that as well.

> Which protocols/ports are used by the P2P DAT protocols?

Dat tries 3282, and falls back to any random unprivileged port if that's not available. It uses UTP and TCP as transport protocols.

**Comment by webdesserts** [comment] 2018-03-16 04:06
@pfrazee Now that we have the ability to seed sites forever, I would like to bump the request for a max upload setting. During the more active part of the day, my upload bandwidth was maxed for good bit.

**Comment by pfrazee** [comment] 2018-09-30 22:53
This got implemented a bit ago! It's in the settings page. Closing

**Closed by pfrazee** 2018-09-30 22:53 UTC
Labels: enhancement
