### ISSUE TITLE
./beaker-browser-0.8.0-x86_64.AppImage not working

### ISSUE THREAD

**Issue by iwwmidatlanticgdc** [beakerbrowser/beaker#1148] opened 2018-09-12 05:57 UTC
Operation System: LMDE 2 
Beaker version: ./beaker-browser-0.8.0-x86_64.AppImage

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/.org.chromium.Chromium.0WiPR5)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_beakerGA0iI4/app/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Object.<anonymous> (/tmp/.mount_beakerGA0iI4/app/resources/app.asar/node_modules/sqlite3/lib/sqlite3.js:190:3)


```

**Comment by pfrazee** [comment] 2018-09-12 16:43
This is a duplicate of https://github.com/beakerbrowser/beaker/issues/796

@iwwmidatlanticgdc try the build I link in https://github.com/beakerbrowser/beaker/issues/796#issuecomment-420712977. If that doesnt work, you'll need to build from source.

**Closed by pfrazee** 2018-09-12 16:43 UTC
Labels: duplicate
